# Generated by Django 3.0.2 on 2020-01-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200117_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file_ref',
        ),
        migrations.AddField(
            model_name='project',
            name='fil',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='image not found', upload_to='images'),
        ),
    ]
