# Generated by Django 3.0.2 on 2020-01-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200117_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fil',
            field=models.FileField(null=True, upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
